[build]
publish = "dist"
command = "npm run build"

[[redirects]]
from = "/report"
to = "/bash/report.sh"
status = 200
force = true

[[redirects]]
from = "/post"
to = "/bash/post.sh"
status = 200
force = true